import 'dotenv/config'
import { sql } from 'drizzle-orm'
import { db, trades } from './db'

// Seed rows use explicit serial ids so the generated tradeId is deterministic
// (TRD-100001..100003) and re-running the seed is idempotent via ON CONFLICT
// (id) DO NOTHING. The tradeId column is generated by Postgres and is not
// inserted by the application.
const rows = [
  {
    id: 1,
    symbol: 'AAPL',
    side: 'BUY' as const,
    quantity: 5000,
    price: 227.45,
    trader: 'JSMITH',
    tradeDate: new Date('2026-08-18T09:15:23Z'),
    status: 'ACTIVE' as const,
  },
  {
    id: 2,
    symbol: 'MSFT',
    side: 'SELL' as const,
    quantity: 1200,
    price: 534.22,
    trader: 'ABROWN',
    tradeDate: new Date('2026-08-18T09:18:54Z'),
    status: 'ACTIVE' as const,
  },
  {
    id: 3,
    symbol: 'TSLA',
    side: 'BUY' as const,
    quantity: 800,
    price: 341.75,
    trader: 'MJONES',
    tradeDate: new Date('2026-08-18T09:20:11Z'),
    status: 'CANCELLED' as const,
  },
]

async function main() {
  console.log('Seeding trades...')
  await db.insert(trades).values(rows).onConflictDoNothing({ target: trades.id })
  // Advance the serial sequence past the explicit ids we inserted, so the
  // next INSERT (which lets Postgres assign the id) does not collide.
  await db.execute(
    sql`SELECT setval('trades_id_seq', GREATEST((SELECT max(id) FROM trades), 1))`,
  )
  console.log('Seed complete.')
}

main()
  .catch((error) => {
    console.error(error)
    process.exitCode = 1
  })
  .finally(() => process.exit())
